services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/data/db

  dba:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
    depends_on:
      - db
    ports:
      - ${DBA_PORT}:8081

  api:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${API_PORT}:80
