services:

  mdb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MDB_PASS}
    volumes:
      - ./data/mdb:/data/db

  dba:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mdb
      ME_CONFIG_BASICAUTH_USERNAME: ${MDB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MDB_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MDB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MDB_PASS}
    depends_on:
      - mdb
    ports:
      - ${DBA_PORT:-8081}:8081

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mdb
    ports:
      - ${API_PORT:-8080}:80
